services:
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    restart: unless-stopped

  shipmentdb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: shipmentdb
    ports:
      - "3306:3306"
    volumes:
      - ./database/shipments.sql:/docker-entrypoint-initdb.d/shipments.sql
    restart: unless-stopped

  orderdb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: orderdb
    ports:
      - "3307:3306"
    volumes:
      - ./database/orders.sql:/docker-entrypoint-initdb.d/orders.sql
    restart: unless-stopped

  trackdb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: trackingdb
    ports:
      - "3308:3306"
    volumes:
      - ./database/tracking.sql:/docker-entrypoint-initdb.d/tracking.sql
    restart: unless-stopped

  routeservice:
    build:
      context: ./route
      no_cache: true
    depends_on:
      - rabbitmq
      - shipmentdb
      - orderdb

  trackservice:
    build:
      context: ./track
      no_cache: true
    depends_on:
      - rabbitmq
      - trackdb
    ports:
      - "8000:80"
    environment:
      DB_HOST: trackdb
      DB_USER: root
      DB_PASS: mypass
      DB_NAME: trackingdb
      RABBITMQ_HOST: localhost  
  

  consolidation:
    build:
      context: ./consolidation
      no_cache: true
    ports:
      - "5002:5002"
    environment:
      DB_HOST: shipmentdb
      DB_USER: root
      DB_PASS: mypass
      DB_NAME: shipmentdb
      RABBITMQ_HOST: rabbitmq
      MAX_WEIGHT_KG: 1000
      MAX_VOLUME_M3: 10
    depends_on:
      - rabbitmq
      - shipmentdb
    restart: unless-stopped